const START = 'START';
const END = 'END';
const CALCULATING = 'CALCULATING';
const SET_NUMBER = 'SET_NUMBER';

const START_ANIMATION = 'START_ANIMATION';
const END_ANIMATION = 'END_ANIMATION';
const START_ADDING_TO_HEAD = 'START_ADDING_TO_HEAD';
const END_ADDING_TO_HEAD = 'END_ADDING_TO_HEAD';
const START_ADDING_TO_TAIL = 'START_ADDING_TO_TAIL';
const END_ADDING_TO_TAIL = 'END_ADDING_TO_TAIL';
const START_REMOVAL_FROM_HEAD = 'START_REMOVAL_FROM_HEAD';
const END_REMOVAL_FROM_HEAD = 'END_REMOVAL_FROM_HEAD';
const START_REMOVAL_FROM_TAIL = 'START_REMOVAL_FROM_TAIL';
const END_REMOVAL_FROM_TAIL = 'END_REMOVAL_FROM_TAIL';
const START_ADDING_BY_INDEX = 'START_ADDING_BY_INDEX';
const END_ADDING_BY_INDEX = 'END_ADDING_BY_INDEX';
const START_REMOVAL_BY_INDEX = 'START_REMOVAL_BY_INDEX';
const END_REMOVAL_BY_INDEX = 'END_REMOVAL_BY_INDEX';

const START_ADDING = 'START_ADDING';
const END_ADDING = 'END_ADDING';
const START_REMOVAL = 'START_REMOVAL';
const END_REMOVAL = 'END_REMOVAL';
const START_CLEANING = 'START_CLEANING';
const END_CLEANING = 'END_CLEANING';

const ADD_LETTERS = 'ADD_LETTERS';

export {START, END, CALCULATING, SET_NUMBER,
    START_ANIMATION, END_ANIMATION, START_ADDING_TO_HEAD, END_ADDING_TO_HEAD, START_ADDING_TO_TAIL, END_ADDING_TO_TAIL,
    START_REMOVAL_FROM_HEAD, END_REMOVAL_FROM_HEAD, START_REMOVAL_FROM_TAIL, END_REMOVAL_FROM_TAIL, 
    START_ADDING_BY_INDEX, END_ADDING_BY_INDEX, START_REMOVAL_BY_INDEX, END_REMOVAL_BY_INDEX,
    START_ADDING, END_ADDING, START_REMOVAL, END_REMOVAL, START_CLEANING, END_CLEANING, ADD_LETTERS
}
